import { 
  Waves, 
  Thermometer, 
  Zap, 
  Droplets, 
  Trees, 
  Bug, 
  ShowerHead, 
  Hammer, 
  Heart, 
  Sparkles, 
  Car, 
  Settings,
  Filter,
  PaintBucket,
  Palette,
  Truck,
  Shield,
  Building2,
  Flame,
  Lightbulb,
  Sofa,
  Grid3x3,
  Star,
  Layers,
  Wine,
  Scroll,
  Sprout,
  Square,
  Tv,
  Plug,
  UtensilsCrossed,
  Music,
  Wind,
  Warehouse,
  Shirt,
  DoorOpen,
  Dumbbell,
  Package,
  Trash2,
  HardHat,
  Hand,
  Baby,
  Key,
  FrameIcon,
  LucideIcon
} from "lucide-react";
import { Category } from "@/data/categories";

export const categoryIconMap: Record<Category, LucideIcon> = {
  "Pool": Waves,
  "HVAC": Thermometer,
  "Electrician": Plug,
  "Grill Cleaning": Flame,
  "Gym Equipment Install/Repair": Dumbbell,
  "Plumbing": Droplets,
  "Painters": PaintBucket,
  "Landscaping": Trees,
  "Landscape Lighting": Lightbulb,
  "Roofing": Building2,
  "Stone Fabricators": Square,
  "Generator": Zap,
  "Pest Control": Bug,
  "Power Washing": ShowerHead,
  "Car Service": Car,
  "Car Wash & Detail": Sparkles,
  "Handyman": Hammer,
  "Pet Grooming": Heart,
  "House Cleaning": Sparkles,
  "House Manager": Building2,
  "Kitchen Cabinetry": Package,
  "Mobile Tire Repair": Car,
  "Mobile Scratch/Dent Repair": Hammer,
  "Appliance Repair": Settings,
  "Auto Transport": Truck,
  "Bartenders": Wine,
  "Bin Cleaning": Trash2,
  "Catering": UtensilsCrossed,
  "Custom Closets": Shirt,
  "DJs": Music,
  "Dryer Vent Cleaning": Wind,
  "Garage Door Repair": DoorOpen,
  "Garage Remodeling": Warehouse,
  "Home Organization": Package,
  "Water Filtration": Filter,
  "Window Cleaning": Sparkles,
  "Window Installation & Repair": FrameIcon,
  "Interior Design": Palette,
  "Moving Company": Truck,
  "Damage Assessment/Restoration": Shield,
  "Carpet/Upholstery Cleaning": Sofa,
  "Screen Doors & Enclosures": Grid3x3,
  "Holiday Lighting": Star,
  "Home Theater & AV": Tv,
  "Turf Installation": Sprout,
  "Pavers": Grid3x3,
  "Wallpaper Installation": Scroll,
  "Window Treatment": Square,
  "Masseuse": Hand,
  "General Contractor": HardHat,
  "Babysitting": Baby,
  "Flooring": Layers,
  "Locksmith": Key,
};

export function getCategoryIcon(category: Category): LucideIcon {
  return categoryIconMap[category] || Settings;
}