import { Category } from "@/data/categories";

// This is the single source of truth for all category emojis across the site
// When adding a new category, update this mapping
export const categoryEmojiMap: Record<string, string> = {
  'all': '🏠',
  'HVAC': '🔧',
  'Pool': '🏊',
  'Landscaping': '🌱',
  'Landscape Lighting': '💡',
  'Plumbing': '🚰',
  'Electrician': '🔌',
  'Generator': '⚡',
  'Pest Control': '🐛',
  'House Cleaning': '🧹',
  'Handyman': '🔨',
  'Roofing': '🏗️',
  'Stone Fabricators': '🪨',
  'General Contractor': '👷',
  'Car Service': '🚗',
  'Car Wash and Detail': '✨',
  'Car Wash & Detail': '✨',
  'Pet Grooming': '🐕',
  'Mobile Tire Repair': '🔧',
  'Mobile Scratch/Dent Repair': '🚘',
  'Appliance Repair': '🔌',
  'Auto Transport': '🚛',
  'Bartenders': '🍸',
  'Bin Cleaning': '🗑️',
  'Catering': '🍽️',
  'Custom Closets': '👔',
  'DJs': '🎧',
  'Dryer Vent Cleaning': '🌬️',
  'Garage Door Repair': '🚪',
  'Garage Remodeling': '🚪',
  'Painters': '🖌️',
  'Grill Cleaning': '🔥',
  'Gym Equipment Install/Repair': '🏋️',
  'Home Organization': '📦',
  'House Manager': '🏢',
  'Kitchen Cabinetry': '🗄️',
  'Power Washing': '🚿',
  'Water Filtration': '💧',
  'Window Cleaning': '🧼',
  'Window Installation & Repair': '🪟',
  'Interior Design': '🛋️',
  'Moving Company': '🚚',
  'Damage Assessment/Restoration': '🛠️',
  'Carpet/Upholstery Cleaning': '🧽',
  'Screen Doors & Enclosures': '🚪',
  'Holiday Lighting': '✨',
  'Home Theater & AV': '📺',
  'Turf Installation': '🌿',
  'Pavers': '🧱',
  'Wallpaper Installation': '📜',
  'Window Treatment': '🪟',
  'Masseuse': '💆',
  'Babysitting': '👶',
  'Flooring': '🪵',
  'Locksmith': '🔑',
  'Tailoring & Alterations': '✂️'
};

export function getCategoryEmoji(category: string): string {
  return categoryEmojiMap[category] || '🏠';
}